import React, { useCallback, useState } from 'react';
import { Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router, useFocusEffect } from 'expo-router';
import { salesService } from '@/modules/sales/service';
import type { SaleSummary } from '@/core/types';
import { useSessionStore } from '@/stores/session';
import { usePreferencesStore } from '@/stores/preferences';
import { formatMoney } from '@/core/money';
import { t } from '@/core/i18n';
import { Badge, Button, Card, Empty, Input, ModalSheet, PageHeader, Screen, Segmented } from '@/shared/ui';
import { useAppTheme } from '@/core/theme/useAppTheme';

function quickRange(kind: string) { const n = new Date(), start = new Date(n), end = new Date(n); if (kind === 'today') start.setHours(0,0,0,0); if (kind === 'yesterday') { start.setDate(start.getDate()-1); start.setHours(0,0,0,0); end.setDate(end.getDate()-1); end.setHours(23,59,59,999); } if (kind === 'week') start.setDate(start.getDate()-7); if (kind === 'month') start.setMonth(start.getMonth()-1); if (kind === 'semester') start.setMonth(start.getMonth()-6); if (kind === 'year') start.setFullYear(start.getFullYear()-1); return { from: start.toISOString(), to: end.toISOString() }; }

export default function Sales() {
  const th = useAppTheme(); const user = useSessionStore((s) => s.user); const currency = usePreferencesStore((s) => s.currency); const locale = usePreferencesStore((s) => s.locale);
  const [rows, setRows] = useState<SaleSummary[]>([]); const [period, setPeriod] = useState('today'); const [filtersOpen, setFiltersOpen] = useState(false); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [status, setStatus] = useState<'COMPLETED'|'VOID'|null>(null); const [method, setMethod] = useState<string|null>(null); const [userId, setUserId] = useState<string|null>(null); const [customerId, setCustomerId] = useState<string|null>(null); const [options, setOptions] = useState<{ users:{id:string;name:string}[]; customers:{id:string;name:string}[] }>({users:[],customers:[]});
  const load = useCallback(() => { if (!user) return; const q = period === 'custom' ? { from: from ? new Date(`${from}T00:00:00`).toISOString() : undefined, to: to ? new Date(`${to}T23:59:59`).toISOString() : undefined } : quickRange(period); void salesService.list(user.id, { ...q, status, userId, customerId, method }).then(setRows); }, [user?.id,period,from,to,status,userId,customerId,method]);
  useFocusEffect(useCallback(() => { load(); if (user) void salesService.filterOptions(user.id).then(setOptions); }, [load,user?.id]));
  const total = rows.filter((r) => r.status === 'COMPLETED').reduce((s,r) => s+r.total,0);
  const periods = ['today','yesterday','week','month','semester','year'].map((k) => ({ label: t(`sales.${k}`), value:k }));
  return <Screen><PageHeader title={t('sales.title')} subtitle={t('premium.sales.historyFiltersAndReversalWithoutDeletingThe')} eyebrow={t('premium.sales.milestone12Sales')} right={<Button compact variant="secondary" icon="options-outline" label={t('premium.sales.filters')} onPress={() => setFiltersOpen(true)} />} />
    <View style={{ flexDirection:'row', flexWrap:'wrap', gap:10 }}><Card style={{flex:1,minWidth:150}}><Text style={{color:th.colors.muted,fontSize:11}}>{t('premium.sales.records')}</Text><Text style={{color:th.colors.heading,fontSize:24,fontWeight:'900'}}>{rows.length}</Text></Card><Card style={{flex:1,minWidth:180}}><Text style={{color:th.colors.muted,fontSize:11}}>{t('premium.sales.completedTotal')}</Text><Text style={{color:th.colors.primary,fontSize:21,fontWeight:'900'}}>{formatMoney(total,currency,locale)}</Text></Card></View>
    <Segmented options={periods} value={period === 'custom' ? 'today' : period} onChange={setPeriod} />
    {rows.length ? rows.map((s) => <Card key={s.id} onPress={() => router.push({ pathname:'/sale/[id]', params:{id:s.id} })}><View style={{flexDirection:'row',alignItems:'center',gap:12}}><View style={{width:46,height:46,borderRadius:15,backgroundColor:s.status==='VOID'?th.colors.dangerSoft:th.colors.successSoft,alignItems:'center',justifyContent:'center'}}><Ionicons name="receipt-outline" size={21} color={s.status==='VOID'?th.colors.danger:th.colors.success}/></View><View style={{flex:1}}><Text style={{color:th.colors.heading,fontWeight:'900'}}>{s.number}</Text><Text style={{color:th.colors.muted,fontSize:11,marginTop:3}}>{new Date(s.created_at).toLocaleString()} · {s.customer_name ?? t('premiumExtra.sales.walkInCustomer')} · {s.user_name}</Text></View><View style={{alignItems:'flex-end',gap:5}}><Text style={{color:th.colors.heading,fontWeight:'900',fontSize:16}}>{formatMoney(s.total,currency,locale)}</Text><Badge label={s.status} tone={s.status==='VOID'?'danger':'success'} /></View></View></Card>) : <Empty label={t('premium.sales.noSalesForThisPeriod')} icon="receipt-outline" />}
    <ModalSheet visible={filtersOpen} title={t('premium.sales.salesFilters')} onClose={() => setFiltersOpen(false)}><Button fullWidth variant={period==='custom'?'secondary':'ghost'} label={t('sales.custom')} icon="calendar-outline" onPress={() => setPeriod('custom')} />{period==='custom'?<><Input label={t('premium.sales.fromYyyyMmDd')} value={from} onChangeText={setFrom}/><Input label={t('premium.sales.toYyyyMmDd')} value={to} onChangeText={setTo}/></>:null}<Text style={{color:th.colors.text,fontWeight:'900'}}>{t('premium.sales.status')}</Text><View style={{flexDirection:'row',gap:6,flexWrap:'wrap'}}><Button label={t('common.all')} variant={!status?'secondary':'ghost'} onPress={() => setStatus(null)}/><Button label={t('premium.sales.completed')} variant={status==='COMPLETED'?'secondary':'ghost'} onPress={() => setStatus('COMPLETED')}/><Button label={t('premium.sales.voided')} variant={status==='VOID'?'secondary':'ghost'} onPress={() => setStatus('VOID')}/></View><Text style={{color:th.colors.text,fontWeight:'900'}}>{t('checkout.method')}</Text><View style={{gap:6}}>{['CASH','CARD','TRANSFER','OTHER'].map((m) => <Button key={m} fullWidth label={t(`methods.${m}`)} variant={method===m?'secondary':'ghost'} onPress={() => setMethod(method===m?null:m)}/>)}</View><Text style={{color:th.colors.text,fontWeight:'900'}}>{t('users.title')}</Text>{options.users.map((u)=><Button key={u.id} fullWidth label={u.name} variant={userId===u.id?'secondary':'ghost'} onPress={() => setUserId(userId===u.id?null:u.id)}/>)}<Text style={{color:th.colors.text,fontWeight:'900'}}>{t('customers.title')}</Text>{options.customers.map((c)=><Button key={c.id} fullWidth label={c.name} variant={customerId===c.id?'secondary':'ghost'} onPress={() => setCustomerId(customerId===c.id?null:c.id)}/>)}<Button fullWidth icon="checkmark" label={t('common.confirm')} onPress={() => {setFiltersOpen(false);load();}} /></ModalSheet>
  </Screen>;
}
