export const PERMISSIONS = [
  'DASHBOARD_VIEW',
  'POS_SELL',
  'CATALOG_PRINT',
  'PRODUCTS_VIEW',
  'PRODUCTS_EDIT',
  'PRODUCT_COST_VIEW',
  'INVENTORY_VIEW',
  'INVENTORY_ADJUST',
  'INVENTORY_PURCHASE',
  'PURCHASES_VIEW',
  'SUPPLIERS_VIEW',
  'SUPPLIERS_EDIT',
  'CUSTOMERS_VIEW',
  'CUSTOMERS_EDIT',
  'CUSTOMER_CREDIT_MANAGE',
  'CASH_OPEN_CLOSE',
  'CASH_MOVEMENTS',
  'SALES_VIEW',
  'SALES_VOID',
  'REPORTS_VIEW',
  'SCANNER_USE',
  'USERS_MANAGE',
  'SETTINGS_MANAGE',
  'BACKUP_MANAGE',
] as const;

export type PermissionCode = typeof PERMISSIONS[number];
export const ADMIN_PERMISSIONS: PermissionCode[] = [...PERMISSIONS];
